# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '主界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import shutil
import os
from detect import main as detect_main

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(953, 594)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 160, 361, 311))
        self.label.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(520, 160, 361, 311))
        self.label_2.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(310, 30, 351, 71))
        self.label_3.setStyleSheet("font: 26pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 500, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 500, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.openimage)
        self.pushButton_2.clicked.connect(self.detect_pic)
    def openimage(self):   #打开图片函数  用于图片选择
        for path in os.listdir('./input'):
            os.remove('./input/{}'.format(path))
        self.imgName, imgType = QFileDialog.getOpenFileName(None, "打开图片", "", "*.jpg;*.png;;All Files(*)")#选择图片，返回文件路径及类别
        print(self.imgName)#打印图片路径
        jpg = QtGui.QPixmap(self.imgName).scaled(self.label.width(), self.label.height())#调整图片大小
        self.label.setPixmap(jpg)#图片在label框中显示
    def detect_pic(self):
        for path in os.listdir('./res'):
            os.remove('./res/{}'.format(path))
        # source_file:源路径, target_ir:目标路径
        shutil.copyfile(self.imgName, './input/input.jpg')
        #os.rename('detect_pic/{}'.format(self.imgName.split('/')[-1]), 'detect_pic/pre.jpg')
        detect_main()
        jpg2 = QtGui.QPixmap('./res/input.jpg').scaled(self.label_2.width(), self.label_2.height())#调整图片大小
        name = self.imgName.split('/')[-1]
        print(name)
        shutil.copyfile('./res/input.jpg', './save_res/{}'.format(name))

        self.label_2.setPixmap(jpg2)#图片在label框中显示
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "安全帽佩戴检测系统"))
        self.pushButton.setText(_translate("Dialog", "选择图片"))
        self.pushButton_2.setText(_translate("Dialog", "开始检测"))

if __name__ == '__main__':
    for path in os.listdir('./input'):
        os.remove('./input/{}'.format(path))
    for path in os.listdir('./res'):
        os.remove('./res/{}'.format(path))
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

